pipeline:
  output_dir: "data"
  output_name: "merged_dialogue_datasets_8k_lt2_mt5"
  seed: 42
  shuffle: true

perplexity:
  enabled: true
  model_name: "Qwen/Qwen2.5-3B-Instruct"
  batch_size: 8

datasets:
  - source: "dailydialog"
    split: "train"
    sample_size: 4000
    min_turns: 5
    min_response_words: 5
    limit_turn: 2
    prompt_style: "cot"
    system_prompt_style: "cot"
    generation_prefix: "<think>"
    add_response_tags: true
    include_system_in_prompt: true

  - source: "empathetic_dialogues"
    split: "train"
    sample_size: 4000
    min_turns: 5
    min_response_words: 5
    limit_turn: 2
    prompt_style: "cot"
    system_prompt_style: "cot"
    generation_prefix: "<think>"
    add_response_tags: true
    include_system_in_prompt: true
